import psycopg2
from scraper import get_information_about_cars
con = psycopg2.connect(
  database="postgres",
  user="postgres",
  password="Marianna+",
  host="127.0.0.1",
  port="5432"
)

print("Database opened successfully")
cur = con.cursor()


def create_table():
    cur.execute('''CREATE TABLE IF NOT EXISTS OLD_CARS 
         (ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        URL VARCHAR(255) NOT NULL,
        TITLE TEXT NOT NULL,
        USD_PRICE INT NOT NULL,
        MILEAGE VARCHAR(50) NOT NULL,
        USERNAME VARCHAR(50) NOT NULL,
        PHONE_NUMBER INT NOT NULL,
        IMG_URL VARCHAR(255) NOT NULL,
        IMG_TOTAL_COUNT INT2 NOT NULL,
        CAR_NUMBER VARCHAR(16),
        CAR_VIN_CODE VARCHAR(20),
        DATETIME_FOUND TIMESTAMP DEFAULT NOW() );''')
    con.commit()


def get_car_info(number):
    cur.execute("SELECT URL From OLD_CARS")
    rows = cur.fetchall()
    car_info = []
    for i in get_information_about_cars(number):
        number = 0
        for row in rows:
            if row[0] == i['url']:
                number = 1
                break
        if number != 1:
            car_info.append(i)
    return car_info


def insert_car_info(number):
    create_table()
    for i in get_car_info(number):
        try:
            cur.execute("""
                INSERT INTO OLD_CARS (TITLE, USD_PRICE, MILEAGE, USERNAME, PHONE_NUMBER,
                IMG_TOTAL_COUNT, CAR_NUMBER, CAR_VIN_CODE, IMG_URL, URL) 
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                    (i['title'], i['usd_price'], i['mileage'], i['username'], i['phone_number'], i['img_total_count'],
                    i['car_number'], i['car_vin_code'], i['img_url'], i['url']))
            con.commit()
        except psycopg2.errors.NotNullViolation:
            print(f"Карточка по ссылке {i['url']} имеет недостающие данные")
        except:
            con.rollback()
    print("Record inserted successfully")
    con.close()




